<?php

function helper_list_droits($droits, $remove_url, $services) {
    echo "<ul>";
    foreach($droits as $droit) {
        echo "<li>".$services[$droit->service]->name." <a href=\"".$remove_url."&right=".$droit->service."\" ><i class=\"icon-remove\"></i></a></li>";
    }
    echo "</ul>";
}

?>

        <div class="row-fluid">
            <div class="hero-unit">
                <h1>Gestion des droits</h1>
            </div>
        </div><!--/row-->
        <div class="accordion" id="rights">
            <div id="user_rights" class="row-fluid accordion-group">
                <div class="accordion-heading">
                    <a class="accordion-toggle" data-toggle="collapse" data-parent="#rights" href="#user_rights_collapse"><h1>Droits des utilisateurs</h1></a>
                </div>
                <div id="user_rights_collapse" class="accordion-body collapse">
                    <div class="accordion-inner">
                        <?php if(isset($this->param['alert']["users"])) {
                            $alert = $this->param['alert']["users"]; ?>
                          <div class="<?php echo $alert['class']; ?>">
                            <strong><?php echo $alert['strong']; ?></strong> <?php echo $alert['message']; ?>
                          </div>
                        <?php } ?>
                        <form class="well form-inline" method="POST" action="<?php echo $this->param['add_user_right']; ?>" >
                          <input type="text" class="input-large typeahead-user" name="usr" placeholder="Rechercher un utilisateur" autocomplete="off" />
                          <input type="hidden" name="usr_id" id="usr_id" />
                          <select class="input-xlarge" name="right">
                            <option value=""></option>
                            <?php foreach($this->param['services'] as $service_name => $service) { ?>
                                <?php if($service->user) { ?>
                                    <option value="<?php echo $service_name; ?>"><?php echo $service->name ?></option>
                                <?php } ?>
                            <?php } ?>
                          </select>
                          <select class="input-xlarge" name="fun_id">
                            <option value=""></option>
                            <?php foreach($this->param['fundations'] as $fun) {
                                $fun_id = $fun->fun_id;
                                $fun_name = $fun->name;
                                ?>
                                <option value="<?php echo $fun_id; ?>"><?php echo $fun_name ?></option>
                            <?php } ?>
                          </select>
                          <button type="submit" class="btn btn-success">Ajouter le droit</button>
                        </form>

                        <div class="accordion" id="user_fundation_rights">
                            <?php foreach($this->param['fundations'] as $fun) {
                                $fun_id = $fun->fun_id;
                                $fun_name = $fun->name;
                                $user_right = $this->param['user_right'][$fun_id];
                                ?>

                                <div id="user_rights_fundation_<?=$fun_id?>" class="row-fluid accordion-group">
                                    <div class="accordion-heading">
                                        <a class="accordion-toggle" data-toggle="collapse" data-parent="#user_fundation_rights" href="#user_rights_fundation_<?=$fun_id?>_collapse"><h2><?php echo $fun_name; ?></h2></a>
                                    </div>
                                </div>
                                <div id="user_rights_fundation_<?=$fun_id?>_collapse" class="accordion-body collapse">
                                    <div class="accordion-inner">
                                        <?php if(count($user_right) == 0) { ?>
                                            <div class="alert alert-info">Aucun droit utilisateur n'a été donné sur cette fundation</div>
                                        <?php } else { ?>
                                            <table class="table table-striped table-bordered">
                                                <thead>
                                                  <tr><th>Login</th><th>Nom</th><th>Prénom</th><th>Droits</th></tr>
                                                </thead>
                                                <tbody>
                                                <?php foreach($user_right as $right) { ?>
                                                  <tr><td><?php echo $right->usr_login; ?></td>
                                                      <td><?php echo $right->usr_lastname; ?></td>
                                                      <td><?php echo $right->usr_firstname; ?></td>
                                                      <td><?php helper_list_droits($right->service,
                                                                    $this->param['remove_user_right']."&usr_id=".$right->usr_id."&fun_id=".$fun_id,
                                                                    $this->param['services']); ?></td>
                                                  </tr>
                                                <?php } ?>
                                                </tbody>
                                            </table>
                                        <?php } ?>
                                    </div>
                                </div>
                            <?php } ?>
                        </div>
                    </div>
                </div>
            </div>

            <div id="application_rights" class="row-fluid accordion-group">
                <div class="accordion-heading">
                    <a class="accordion-toggle" data-toggle="collapse" data-parent="#application_rights" href="#application_rights_collapse"><h1>Droits des Applications</h1></a>
                </div>
                <div id="application_rights_collapse" class="accordion-body collapse">
                    <div class="accordion-inner">
                    <?php if(isset($this->param['alert']["applications"])) {
                        $alert = $this->param['alert']["applications"]; ?>
                      <div class="<?php echo $alert['class']; ?>">
                        <strong><?php echo $alert['strong']; ?></strong> <?php echo $alert['message']; ?>
                      </div>
                    <?php } ?>
                    <form class="well form-inline" method="POST" action="<?php echo $this->param['add_app_right']; ?>" >
                      <select class="input-xlarge" name="app_id">
                        <option value=""></option>
                        <?php foreach($this->param['applications'] as $app) { ?>
                            <option value="<?php echo $app->app_id; ?>"><?php echo $app->app_name." - ".$app->app_desc; ?></option>
                        <?php } ?>
                      </select>
                      <select class="input-xlarge" name="right">
                        <option value=""></option>
                        <?php foreach($this->param['services'] as $service_name => $service) { ?>
                            <?php if($service->app) { ?>
                                <option value="<?php echo $service_name; ?>"><?php echo $service->name ?></option>
                            <?php } ?>
                        <?php } ?>
                      </select>
                      <select class="input-xlarge" name="fun_id">
                        <option value=""></option>
                        <?php foreach($this->param['fundations'] as $fun) {
                            $fun_id = $fun->fun_id;
                            $fun_name = $fun->name;
                            ?>
                            <option value="<?php echo $fun_id; ?>"><?php echo $fun_name ?></option>
                        <?php } ?>
                      </select>
                      <button type="submit" class="btn btn-success">Ajouter le droit</button>
                    </form>
                        <div class="accordion" id="application_fundation_rights">
                            <?php foreach($this->param['fundations'] as $fun) {
                                $fun_id = $fun->fun_id;
                                $fun_name = $fun->name;
                                if($fun_id) {
                                    $app_right = $this->param['app_right'][$fun_id];
                                } else {
                                    $app_right = $this->param['app_right'][""];
                                } ?>

                                <div id="application_rights_fundation_<?=$fun_id?>" class="row-fluid accordion-group">
                                    <div class="accordion-heading">
                                        <a class="accordion-toggle" data-toggle="collapse" data-parent="#application_fundation_rights" href="#application_rights_fundation_<?=$fun_id?>_collapse"><h2><?php echo $fun_name; ?></h2></a>
                                    </div>
                                </div>
                                <div id="application_rights_fundation_<?=$fun_id?>_collapse" class="accordion-body collapse">
                                    <div class="accordion-inner">
                                        <?php if(count($app_right) == 0) { ?>
                                            <div class="alert alert-info">Aucun droit application n'a été donné sur cette fundation</div>
                                        <?php } else { ?>
                                            <table class="table table-striped table-bordered">
                                                <thead>
                                                  <tr><th>Nom</th><th>Description</th><th>Droits</th></tr>
                                                </thead>
                                                <tbody>
                                                <?php foreach($app_right as $right) { ?>
                                                  <tr><td><?php echo $this->param['applications'][$right->app_id]->app_name; ?></td>
                                                      <td><?php echo $this->param['applications'][$right->app_id]->app_desc; ?></td>
                                                      <td><?php helper_list_droits($right->service,
                                                                        $this->param['remove_app_right']."&app_id=".$right->app_id."&fun_id=".$fun_id,
                                                                        $this->param['services']); ?></td>
                                                  </tr>
                                                <?php } ?>
                                                </tbody>
                                            </table>
                                        <?php } ?>
                                    </div>
                                </div>
                            <?php } ?>
                        </div>
                    </div>
                </div>
            </div>
            <br />
          </div>

        </div>
